### ISSUE TITLE
Memory Leak and "HasShutDownFinished" even false

### ISSUE THREAD

**Issue by enricobenedos** [jacobbo/WebEye#47]
Hi Guys,

thank you for your good work!

I use this DLL in a my WPF application. I have a user control with the _streamplayercontrol and I load it in a slideshow with other usercontrol in the MainWindow.

After some minutes than the slideshow works I receive this error : 

```
System.ComponentModel.Win32Exception: 'Not enough storage is available to process this command'
   at WebEye.Controls.Wpf.StreamPlayerControl.StreamPlayerProxy.LoadDll() in D:\dev\GitHub\WebEye\StreamPlayerControl\WPF\StreamPlayerControl\StreamPlayerControl\StreamPlayerProxy.cs:line 196
   at WebEye.Controls.Wpf.StreamPlayerControl.StreamPlayerProxy..ctor() in D:\dev\GitHub\WebEye\StreamPlayerControl\WPF\StreamPlayerControl\StreamPlayerControl\StreamPlayerProxy.cs:line 23
   at WebEye.Controls.Wpf.StreamPlayerControl.StreamPlayerControl.CreateAndInitializePlayer() in D:\dev\GitHub\WebEye\StreamPlayerControl\WPF\StreamPlayerControl\StreamPlayerControl\StreamPlayerControl.xaml.cs:line 194
   at WebEye.Controls.Wpf.StreamPlayerControl.StreamPlayerControl.StartPlay(Uri uri, TimeSpan connectionTimeout, RtspTransport transport, RtspFlags flags) in D:\dev\GitHub\WebEye\StreamPlayerControl\WPF\StreamPlayerControl\StreamPlayerControl\StreamPlayerControl.xaml.cs:line 79
   at WebEye.Controls.Wpf.StreamPlayerControl.StreamPlayerControl.StartPlay(Uri uri) in D:\dev\GitHub\WebEye\StreamPlayerControl\WPF\StreamPlayerControl\StreamPlayerControl\StreamPlayerControl.xaml.cs:line 58
   at FCSSupervisorGUI.UserControlsV.UCCameraViewerWebEye.<>c__DisplayClass6_1.<Btn_Click>b__3() in C:\Projects\FCSSystem\Supervisore.NET\FCSSupervisorGUI\FCSSupervisorGUI\UserControlsV\UCCameraViewerWebEye.xaml.cs:line 109
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
```
When this error happened there is even a visible memory leak.

To solve it, in my user control unload event I try to attend that the dispatcher has shutdown finished but the property is always false.

Thank you!

**Comment by jacobbo** [comment]
Hi Enrico, it looks like you recreating the control a number of times. Try to reuse the control instance instead.

**Comment by enricobenedos** [comment]
Sorry but I haven't the possibility to reuse the control. I need to create and destroy it. Have you got any suggestion? Something like Dispose()or ReleaseComObject()? If you like I can provide to create an example for you to be more clearly.

**Comment by jacobbo** [comment]
Well, then you could try to move the control to a separate window and close the window when you do not need it any more.

**Comment by enricobenedos** [comment]
Thank you for your answer! Finally I use the first method : I create a list of players in a static properties in a global class. When I need the pre-initialized players I scroll all the list an put the players in the relative locations. When I change page simply stop the player form avoid network consumptions.
I hope you can improve your memory leaks beacuse this library is very beautiful!
Bye
